repos:
  - repo: git://github.com/santander-digital-assets/pre-commit-terraform
    rev: v1.31.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      - id: terraform_tflint
