name: Lint GitHub Actions

on:
  push:
    paths:
      - '.github/workflows/*.ya?ml'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/*.ya?ml'

concurrency:
  group: "actionlint-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: lint wit zizmor
        run: |
          pipx install zizmor
          zizmor --gh-token ${{ secrets.GITHUB_TOKEN }} --format sarif . > results.sarif || true

      - name: Upload SARIF file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: results.sarif
          path: results.sarif

  upload:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Download SARIF file
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: results.sarif
          path: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@76621b61decf072c1cee8dd1ce2d2a82d33c17ed # v3.29.5
        with:
          sarif_file: results.sarif
          category: actions-zizmor
