name: Build lambdas

on:
  pull_request:
    branches:
      - main
    paths:
      - 'lambdas/**'
      - '.github/workflows/lambda.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    container:
      image: node:${{ matrix.node }}
    defaults:
      run:
        working-directory: ./lambdas

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run prettier
        run: yarn format-check
      - name: Run linter
        run: yarn lint
      - name: Run tests
        id: test
        run: yarn test
      - name: Build distribution
        run: yarn build
      - name: Upload coverage report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ failure() }}
        with:
          name: coverage-reports
          path: ./**/coverage
          retention-days: 5
