name: Build lambdas

on:
  pull_request:
    branches:
      - main
    paths:
      - 'lambdas/**'
      - '.github/workflows/lambda.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    container:
      image: node:${{ matrix.node }}
    defaults:
      run:
        working-directory: ./lambdas

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run prettier
        run: yarn format-check
      - name: Run linter
        run: yarn lint
      - name: Run tests
        id: test
        run: yarn test
      - name: Build distribution
        run: yarn build
      - name: Upload coverage report
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        if: ${{ failure() }}
        with:
          name: coverage-reports
          path: ./**/coverage
          retention-days: 5
